server:
  port: 8080
spring:
  application:
    name: "backend-SBDCPC"
  devtools:
    add-properties: false
    rabbitmq:
      host: "localhost"
      port: 5672
      username: "guest"
      password: "guest"
      virtual-host: "/"
  profiles:
    include: null
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: "mongodb+srv://juanpablosanchez744:admin@cluster0.ejqpwut.mongodb.net/reto"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
